spring:
  datasource:
    url: jdbc:h2:mem:identity_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  flyway:
    enabled: false  # Disable Flyway for H2
  
  redis:
    host: localhost
    port: 6380
    password: ""
    timeout: 2000ms

# JWT Configuration
jwt:
  secret: mySecretKeyForDevelopmentOnly123456789012345678901234567890
  access-token-expiration-ms: 3600000
  refresh-token-expiration-ms: 2592000000
  remember-me-expiration-ms: 7776000000

# Disable management endpoints that require metrics
management:
  tracing:
    enabled: false
  metrics:
    enabled: false