# Production Configuration for Identity Service
# This configuration optimizes for security, performance, and production readiness

logging:
  level:
    # Application logging
    com.focushive.identity: INFO
    root: WARN
    
    # Spring framework - minimal logging in production
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.security.oauth2: WARN
    org.springframework.data: WARN
    
    # Hibernate - no SQL logging in production
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    
    # External libraries
    org.apache.kafka: WARN
    org.postgresql: ERROR
    org.springframework.data.redis: ERROR
    
  pattern:
    # Production logging pattern
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# JPA Production Settings
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        
# Management endpoints - restrict in production
management:
  endpoints:
    web:
      exposure:
        # Only expose essential endpoints in production
        include: health,info,metrics,prometheus
  endpoint:
    health:
      # Don't show details in production for security
      show-details: when_authorized
      roles: ADMIN
  metrics:
    export:
      prometheus:
        enabled: true