# Analytics Service Configuration
spring:
  application:
    name: analytics-service
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/analytics_service
    username: ${DB_USERNAME:analytics_user}
    password: ${DB_PASSWORD:analytics_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      validation-timeout: 5000
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
  
  # Flyway Configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    schemas: public
  
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
      database: 3
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms
  
  # Security Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8081/identity}
          jwk-set-uri: ${JWT_ISSUER_URI:http://localhost:8081/identity}/oauth2/jwks

# Server Configuration
server:
  port: ${SERVER_PORT:8085}
  servlet:
    context-path: /analytics
  error:
    include-message: always
    include-binding-errors: always

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.focushive.analytics: ${LOG_LEVEL:INFO}
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Custom Application Configuration
analytics:
  # Data aggregation settings
  aggregation:
    daily-summary-hour: 2  # Run daily summary at 2 AM
    weekly-summary-day: 0  # Run weekly summary on Sunday
    cleanup-retention-days: 365  # Keep data for 1 year
  
  # Performance settings
  performance:
    batch-size: 1000
    max-results: 10000
    cache-ttl: PT1H
  
  # Export settings
  export:
    max-records: 50000
    csv-batch-size: 1000
    temp-file-cleanup-hours: 24

# Profile-specific Configuration
---
spring:
  config:
    activate:
      on-profile: test
  
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  
  flyway:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: prod
  
  jpa:
    show-sql: false
  
logging:
  level:
    com.focushive.analytics: INFO
    org.springframework.security: WARN