apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: focushive-notification
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: focushive
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8083"
    prometheus.io/path: "/actuator/prometheus"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  - name: https
    port: 443
    targetPort: http
    protocol: TCP
  - name: metrics
    port: 8083
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-headless
  namespace: focushive-notification
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: focushive
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8083
    targetPort: http
    protocol: TCP
  selector:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: focushive-notification
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: focushive
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: focushive-notification
  name: notification-service-role
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notification-service-rolebinding
  namespace: focushive-notification
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
subjects:
- kind: ServiceAccount
  name: notification-service
  namespace: focushive-notification
roleRef:
  kind: Role
  name: notification-service-role
  apiGroup: rbac.authorization.k8s.io