version: '3.9'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: focushive-db
    environment:
      POSTGRES_DB: focushive
      POSTGRES_USER: focushive_user
      POSTGRES_PASSWORD: focushive_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U focushive_user -d focushive"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for presence pub/sub
  redis:
    image: redis:7-alpine
    container_name: focushive-redis
    command: redis-server --requirepass focushive_pass
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: focushive-backend
    ports:
      - "8080:8080"
    environment:
      # Database
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: focushive
      DB_USER: focushive_user
      DB_PASSWORD: focushive_pass
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: focushive_pass
      # Application
      SERVER_PORT: 8080
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRATION: 86400000
      LOG_LEVEL: INFO
      SHOW_SQL: "false"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # React Frontend (Vite dev server)
  web:
    build:
      context: ./frontend/web
      dockerfile: Dockerfile
      target: development
    container_name: focushive-web
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8080
    volumes:
      - ./frontend/web:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: focushive-network