apiVersion: v2
name: notification-service
description: A Helm chart for FocusHive Notification Service
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - notification
  - microservice
  - spring-boot
  - focushive
  - messaging
  - email

home: https://github.com/focushive/notification-service
sources:
  - https://github.com/focushive/notification-service

maintainers:
  - name: FocusHive Team
    email: dev@focushive.app
    url: https://focushive.app

annotations:
  category: Application
  licenses: MIT
  
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
    alias: postgres
  
  - name: redis
    version: "18.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  
  - name: rabbitmq
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
  
  - name: prometheus
    version: "25.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.prometheus.enabled
  
  - name: grafana
    version: "7.x.x"
    repository: "https://grafana.github.io/helm-charts"
    condition: monitoring.grafana.enabled