apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials
  database-username: {{ .Values.secrets.database.username | b64enc | quote }}
  database-password: {{ .Values.secrets.database.password | b64enc | quote }}
  
  # Redis password
  redis-password: {{ .Values.secrets.redis.password | b64enc | quote }}
  
  # RabbitMQ credentials
  rabbitmq-username: {{ .Values.secrets.rabbitmq.username | b64enc | quote }}
  rabbitmq-password: {{ .Values.secrets.rabbitmq.password | b64enc | quote }}
  
  # AWS SES SMTP credentials
  aws-ses-username: {{ .Values.secrets.email.awsSesUsername | b64enc | quote }}
  aws-ses-password: {{ .Values.secrets.email.awsSesPassword | b64enc | quote }}