apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.management.enabled }}
    - port: {{ .Values.service.management.port }}
      targetPort: management
      protocol: TCP
      name: management
    {{- end }}
  selector:
    {{- include "notification-service.selectorLabels" . | nindent 4 }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
---
{{- if .Values.service.headless.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-service.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
    service-type: headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.management.enabled }}
    - port: {{ .Values.service.management.port }}
      targetPort: management
      protocol: TCP
      name: management
    {{- end }}
  selector:
    {{- include "notification-service.selectorLabels" . | nindent 4 }}
  publishNotReadyAddresses: true
{{- end }}