services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: focushive-db
    environment:
      POSTGRES_DB: focushive
      POSTGRES_USER: focushive_user
      POSTGRES_PASSWORD: focushive_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U focushive_user -d focushive"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis for presence pub/sub
  redis:
    image: redis:7-alpine
    container_name: focushive-redis
    command: redis-server --requirepass focushive_pass
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "focushive_pass", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Identity Service Database
  identity-db:
    image: postgres:16-alpine
    container_name: identity-db
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: identity_user
      POSTGRES_PASSWORD: identity_pass
    ports:
      - "5433:5432"
    volumes:
      - identity_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U identity_user -d identity_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Identity Service Redis
  identity-redis:
    image: redis:7-alpine
    container_name: identity-redis
    command: redis-server --requirepass identity_redis_pass
    ports:
      - "6380:6379"
    volumes:
      - identity_redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "identity_redis_pass", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Identity Service (Spring Boot)
  identity-service:
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    container_name: identity-service
    ports:
      - "8081:8081"
    environment:
      # Database
      DB_HOST: identity-db
      DB_PORT: 5432
      DB_NAME: identity_db
      DB_USER: identity_user
      DB_PASSWORD: identity_pass
      # Redis
      REDIS_HOST: identity-redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: identity_redis_pass
      # Security
      KEY_STORE_PASSWORD: changeme
      PRIVATE_KEY_PASSWORD: changeme
      FOCUSHIVE_CLIENT_SECRET: secret
      # CORS
      CORS_ORIGINS: http://192.168.2.3:3000,http://192.168.2.3:5173,http://192.168.2.3:8080,http://localhost:3000,http://localhost:5173,http://localhost:8080
      # Application
      SERVER_PORT: 8081
      LOG_LEVEL: INFO
      SHOW_SQL: "false"
    depends_on:
      identity-db:
        condition: service_healthy
      identity-redis:
        condition: service_healthy
    restart: unless-stopped

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: focushive-backend
    ports:
      - "8080:8080"
    environment:
      # Database
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: focushive
      DB_USER: focushive_user
      DB_PASSWORD: focushive_pass
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: focushive_pass
      # Identity Service
      IDENTITY_SERVICE_URL: http://identity-service:8081
      # Application
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET}  # CRITICAL: Must be set in environment - no default for security
      JWT_EXPIRATION: 86400000
      LOG_LEVEL: INFO
      SHOW_SQL: "false"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      identity-service:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  identity_db_data:
  identity_redis_data:

networks:
  default:
    name: focushive-network