spring:
  cloud:
    gateway:
      routes:
        # Identity Service - Docker network
        - id: identity-service
          uri: http://identity-service:8081
          predicates:
            - Path=/auth/**, /oauth2/**, /userinfo, /profile/**, /personas/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: identity-service-cb
                fallbackUri: forward:/fallback/identity
            - StripPrefix=0
        
        # FocusHive Backend - Docker network
        - id: focushive-backend
          uri: http://focushive-backend:8080
          predicates:
            - Path=/hives/**, /presence/**, /timers/**, /focus-sessions/**, /ws/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 200
                redis-rate-limiter.burstCapacity: 400
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: focushive-backend-cb
                fallbackUri: forward:/fallback/focushive
            - JwtAuthenticationFilter
            - StripPrefix=0
        
        # Music Service - Docker network
        - id: music-service
          uri: http://music-service:8082
          predicates:
            - Path=/music/**, /playlists/**, /spotify/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: music-service-cb
                fallbackUri: forward:/fallback/music
            - JwtAuthenticationFilter
            - StripPrefix=0
        
        # Notification Service - Docker network
        - id: notification-service
          uri: http://notification-service:8083
          predicates:
            - Path=/notifications/**, /preferences/notifications/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: notification-service-cb
                fallbackUri: forward:/fallback/notifications
            - JwtAuthenticationFilter
            - StripPrefix=0
        
        # Chat Service - Docker network
        - id: chat-service
          uri: http://chat-service:8084
          predicates:
            - Path=/chat/**, /messages/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 500
                redis-rate-limiter.burstCapacity: 1000
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: chat-service-cb
                fallbackUri: forward:/fallback/chat
            - JwtAuthenticationFilter
            - StripPrefix=0
        
        # Analytics Service - Docker network
        - id: analytics-service
          uri: http://analytics-service:8085
          predicates:
            - Path=/analytics/**, /reports/**, /insights/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: analytics-service-cb
                fallbackUri: forward:/fallback/analytics
            - JwtAuthenticationFilter
            - StripPrefix=0
        
        # Forum Service - Docker network
        - id: forum-service
          uri: http://forum-service:8086
          predicates:
            - Path=/forum/**, /posts/**, /topics/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 100
                redis-rate-limiter.burstCapacity: 200
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: forum-service-cb
                fallbackUri: forward:/fallback/forum
            - JwtAuthenticationFilter
            - StripPrefix=0
        
        # Buddy Service - Docker network
        - id: buddy-service
          uri: http://buddy-service:8087
          predicates:
            - Path=/buddies/**, /partnerships/**, /accountability/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 50
                redis-rate-limiter.burstCapacity: 100
                redis-rate-limiter.requestedTokens: 1
            - name: CircuitBreaker
              args:
                name: buddy-service-cb
                fallbackUri: forward:/fallback/buddy
            - JwtAuthenticationFilter
            - StripPrefix=0

  # Redis configuration for Docker
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms
      connect-timeout: 2000ms

  # OAuth2 configuration for Docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://identity-service:8081/oauth2/jwks
          issuer-uri: http://identity-service:8081

# Logging for Docker environment
logging:
  level:
    com.focushive.gateway: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.security: WARN
    org.springframework.web.reactive.function.client: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"