# Prometheus Configuration for FocusHive Notification Service
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'focushive-notification-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  # Notification Service Application
  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['focushive-notification-service-app:8083']
        labels:
          service: 'notification-service'
          type: 'application'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL Exporter (if deployed)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          service: 'postgres'
          database: 'notification_service'

  # Redis Exporter (if deployed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          service: 'redis'
          cache: 'notification'

  # RabbitMQ
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['focushive-notification-service-rabbitmq:15692']
        labels:
          service: 'rabbitmq'
          queue: 'notification'

  # Node Exporter for system metrics (if deployed)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'