# Development Configuration for FocusHive Backend
# This profile can be used for development-specific overrides

spring:
  # Development-specific JPA settings
  jpa:
    hibernate:
      ddl-auto: update  # Allow automatic schema updates in development
    show-sql: true  # Show SQL queries for debugging
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

# Enable detailed logging for development
logging:
  level:
    com.focushive: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.data: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    feign: DEBUG

# Enable all management endpoints for development
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Application features - enable more in development
app:
  features:
    forum:
      enabled: true
    buddy:
      enabled: true
    analytics:
      enabled: true
    authentication:
      enabled: true
    health:
      enabled: true
    # Keep Redis disabled until infrastructure is ready
    redis:
      enabled: false