apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: identity-service-hpa
  namespace: focushive
  labels:
    app: identity-service
    version: v1
    tier: backend
    component: authentication
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: identity-service
  
  # Scaling configuration
  minReplicas: 3  # Always maintain at least 3 replicas for HA
  maxReplicas: 20  # Scale up to 20 replicas under high load
  
  # Scaling behavior configuration
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60  # Wait 1 minute before scaling up again
      policies:
      - type: Percent
        value: 100  # Double the number of replicas
        periodSeconds: 60
      - type: Pods
        value: 4  # Or add 4 pods
        periodSeconds: 60
      selectPolicy: Max  # Use the more aggressive policy
    
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 minutes before scaling down
      policies:
      - type: Percent
        value: 50  # Remove 50% of replicas
        periodSeconds: 60
      - type: Pods
        value: 2  # Or remove 2 pods
        periodSeconds: 60
      selectPolicy: Min  # Use the more conservative policy

  # Metrics for autoscaling
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70  # Scale up when CPU > 70%
  
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80  # Scale up when memory > 80%
  
  # Custom metric: HTTP requests per second
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"  # Scale up when > 100 RPS per pod
  
  # Custom metric: Authentication requests rate
  - type: Pods
    pods:
      metric:
        name: auth_requests_per_minute
      target:
        type: AverageValue
        averageValue: "50"  # Scale up when > 50 auth requests per minute per pod

---
# Vertical Pod Autoscaler (optional, for resource right-sizing)
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: identity-service-vpa
  namespace: focushive
  labels:
    app: identity-service
    version: v1
    tier: backend
    component: authentication
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: identity-service
  
  # VPA update policy
  updatePolicy:
    updateMode: "Auto"  # Automatically apply recommendations
    # Options: "Off", "Initial", "Auto"
  
  # Resource policy
  resourcePolicy:
    containerPolicies:
    - containerName: identity-service
      # Don't scale below these minimums
      minAllowed:
        cpu: 100m
        memory: 256Mi
      # Don't scale above these maximums
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      # Which resources to manage
      controlledResources: ["cpu", "memory"]
      # How VPA should handle resource scaling
      controlledValues: RequestsAndLimits

---
# Pod Disruption Budget - Ensure availability during updates
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: identity-service-pdb
  namespace: focushive
  labels:
    app: identity-service
    version: v1
    tier: backend
    component: authentication
spec:
  # Ensure at least 2 pods are always available
  minAvailable: 2
  # Alternative: maxUnavailable: 1
  
  selector:
    matchLabels:
      app: identity-service
      version: v1

---
# ServiceMonitor for Prometheus metrics collection
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: identity-service-metrics
  namespace: focushive
  labels:
    app: identity-service
    version: v1
    tier: backend
    component: authentication
spec:
  selector:
    matchLabels:
      app: identity-service
  endpoints:
  - port: actuator
    path: /actuator/prometheus
    interval: 30s
    scrapeTimeout: 10s
    # Custom metrics relabeling
    metricRelabelings:
    - sourceLabels: [__name__]
      regex: 'identity_service_(.*)'
      targetLabel: __name__
      replacement: '${1}'
    - sourceLabels: [instance]
      targetLabel: pod
    - targetLabel: service
      replacement: identity-service

---
# PrometheusRule for alerting
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: identity-service-alerts
  namespace: focushive
  labels:
    app: identity-service
    version: v1
    tier: backend
    component: authentication
spec:
  groups:
  - name: identity-service
    interval: 30s
    rules:
    # High error rate alert
    - alert: IdentityServiceHighErrorRate
      expr: rate(http_server_requests_seconds_count{job="identity-service",status=~"5.."}[5m]) > 0.1
      for: 2m
      labels:
        severity: critical
        service: identity-service
      annotations:
        summary: "High error rate in Identity Service"
        description: "Identity Service has error rate above 10% for more than 2 minutes"
    
    # High response time alert
    - alert: IdentityServiceHighLatency
      expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket{job="identity-service"}[5m])) > 1
      for: 5m
      labels:
        severity: warning
        service: identity-service
      annotations:
        summary: "High latency in Identity Service"
        description: "95th percentile latency is above 1 second for more than 5 minutes"
    
    # Database connection issues
    - alert: IdentityServiceDatabaseConnectionIssues
      expr: hikaricp_connections_active{job="identity-service"} / hikaricp_connections_max{job="identity-service"} > 0.8
      for: 2m
      labels:
        severity: warning
        service: identity-service
      annotations:
        summary: "Identity Service database connections high"
        description: "Database connection pool usage is above 80%"
    
    # Redis connection issues
    - alert: IdentityServiceRedisConnectionIssues
      expr: up{job="identity-service-redis"} == 0
      for: 1m
      labels:
        severity: critical
        service: identity-service
      annotations:
        summary: "Identity Service Redis connection down"
        description: "Redis connection is down for Identity Service"
    
    # High CPU usage
    - alert: IdentityServiceHighCPU
      expr: rate(container_cpu_usage_seconds_total{pod=~"identity-service-.*"}[5m]) > 0.8
      for: 10m
      labels:
        severity: warning
        service: identity-service
      annotations:
        summary: "High CPU usage in Identity Service"
        description: "CPU usage is above 80% for more than 10 minutes"
    
    # High memory usage
    - alert: IdentityServiceHighMemory
      expr: container_memory_usage_bytes{pod=~"identity-service-.*"} / container_spec_memory_limit_bytes{pod=~"identity-service-.*"} > 0.9
      for: 5m
      labels:
        severity: critical
        service: identity-service
      annotations:
        summary: "High memory usage in Identity Service"
        description: "Memory usage is above 90% for more than 5 minutes"
    
    # Authentication failures
    - alert: IdentityServiceAuthenticationFailures
      expr: rate(authentication_attempts_total{job="identity-service",result="failure"}[5m]) > 10
      for: 2m
      labels:
        severity: warning
        service: identity-service
      annotations:
        summary: "High authentication failure rate"
        description: "Authentication failure rate is above 10 per second"
    
    # Pod restart alert
    - alert: IdentityServicePodRestarting
      expr: rate(kube_pod_container_status_restarts_total{pod=~"identity-service-.*"}[15m]) > 0
      for: 0m
      labels:
        severity: warning
        service: identity-service
      annotations:
        summary: "Identity Service pod restarting"
        description: "Identity Service pod {{ $labels.pod }} is restarting"
    
    # Service availability alert
    - alert: IdentityServiceDown
      expr: up{job="identity-service"} == 0
      for: 1m
      labels:
        severity: critical
        service: identity-service
      annotations:
        summary: "Identity Service is down"
        description: "Identity Service has been down for more than 1 minute"