# Production Configuration for FocusHive Backend
# This configuration optimizes for security, performance, and production readiness

logging:
  level:
    # Application logging
    com.focushive: INFO
    root: WARN
    
    # Spring framework - minimal logging in production
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.data: WARN
    
    # External libraries - minimal logging
    feign: NONE
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.apache.kafka: WARN
    org.postgresql: ERROR
    
    # Redis - error only
    org.springframework.data.redis: ERROR
    
  pattern:
    # Production logging pattern with correlation IDs
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId:-}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId:-}] %logger{36} - %msg%n"

# JPA Production Settings
spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
        
# Feign Production Settings
feign:
  client:
    config:
      default:
        loggerLevel: none
      identity-service:
        loggerLevel: none

# Management endpoints - restrict in production
management:
  endpoints:
    web:
      exposure:
        # Only expose essential endpoints in production
        include: health,info,metrics,prometheus
  endpoint:
    health:
      # Don't show details in production for security
      show-details: when_authorized
      roles: ADMIN
  metrics:
    export:
      prometheus:
        enabled: true