spring:
  profiles:
    active: dev
    include:
      - common

  # Development database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db_dev
    username: notification_user_dev
    password: dev_password_123
    hikari:
      connection-timeout: 20000
      minimum-idle: 2
      maximum-pool-size: 5
      idle-timeout: 300000
      max-lifetime: 600000

  # Development Redis configuration
  data:
    redis:
      host: localhost
      port: 6379
      password: ""
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 4
          max-idle: 4
          min-idle: 1

  # Development RabbitMQ configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /dev

  # Development mail configuration (use Mailhog for testing)
  mail:
    host: localhost
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  # Development security configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/focushive-dev
          jwk-set-uri: http://localhost:8081/auth/realms/focushive-dev/protocol/openid-connect/certs

  # Enable H2 console for development
  h2:
    console:
      enabled: false

# Development server configuration
server:
  port: 8083

# Development management configuration
management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Development notification configuration
notification:
  email:
    from: dev@focushive.local
    enabled: true
  digest:
    schedule: "0 */5 * * * *"  # Every 5 minutes for testing
    batch-size: 10
  retry:
    max-attempts: 2
    delay: 500

# Development logging configuration
logging:
  level:
    com.uol.focushive.notificationservice: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
  file:
    name: logs/notification-service-dev.log

# Development CORS configuration
cors:
  allowed-origins: "http://localhost:3000,http://localhost:3001"
  allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
  allowed-headers: "*"
  allow-credentials: true

# Development monitoring configuration
management:
  tracing:
    sampling:
      probability: 1.0  # Sample all requests in development
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans

# Development-specific features
debug: true

# Springdoc OpenAPI configuration for development
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true